### PR TITLE
chore: fix links in README to https

### PR DESCRIPTION
**Pull request by eseidel**
Pub was lowering the score due to this.

Also ran prettier over the README.md which changed a few things.

### CODE REVIEW

**Comment by Levi-Lesches** [comment]
I was actually going to give the README a full update since it still describes how to use the old API and not the new one... I'll link to that PR and ask you to review if you'd like

**Comment by eseidel** [comment]
Go for it.  I was just looking for an AStar again this evening, noticed the pub-score problems (also, you should register yourself as a publisher) and decided to send you a couple PRs.

**Comment by Levi-Lesches** [comment]
Yeah thanks, I hadn't realized the lower score. 

> also, you should register yourself as a publisher

I was wondering about that -- what's the recommended process for individuals who don't have a personal website?

**Comment by eseidel** [comment]
I don't know.  I suspect you can use your github as a personal website?  Or is it per-domain?

**Comment by Levi-Lesches** [comment]
Sadly github pages aren't supported as you need to be able to control DNS records, which isn't possible with GitHub afaik. That's why I've been putting it off -- since you can only transfer packages _to_ a verified publisher, and not back from one, I'd have to continue to own and keep that website somewhat up-to-date over the years, or risk all my packages being...  I don't really know what happens to them after that. 

Still looking into it long-term, and if I do, I'll migrate everything

**Comment by eseidel** [comment]
You definitely can publish to a custom dns from github pages.  https://shorebird.dev/ is hosted on github pages for example. 🤣. You do have to pay the $15/year for a DNS record of course.

**Comment by Levi-Lesches** [comment]
Right, I meant you have to buy and keep your own domain. I'll probably get to that one of these days.... Anyways, closing this from #21

**Pull request closed without merging**
